name: CI
on: [push, pull_request]
jobs:
  linter:
    name: Run-eslint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      
      - name: Install Node v12
        uses: actions/setup-node@master
        with:
          node-version: 12
        
      - name: Install dependencies
        run: npm install

      - name: Run Eslint
        run: npm run lint
